### ISSUE TITLE
Alexa et Livebox

### ISSUE THREAD

**Issue by bedope** [Aymkdn/assistant-livebox#2]
Bonjour,

J'ai suivi la procédure avec un syno et il semble prêt à écouter les commandes via PushBullet
Cependant, l'Echo Dot d'Amazon ayant Alexa ne semble pas l'entendre dde la sorte.

Y a t-il quelque chose à faire en plus pour qu'Alexa vienne récupérer les éléments sur le Syno ?

Merci par avance.

**Comment by Aymkdn** [comment]
> Cependant, l'Echo Dot d'Amazon ayant Alexa ne semble pas l'entendre dde la sorte

Faut m'en dire plus....

Tu as créé une applet IFTTT ? Si oui tu as mis quoi dedans ? Quel trigger, quelle commande? Etc...

**Comment by Aymkdn** [comment]
Demain je vais essayer de prendre du temps pour pré-créer des applets (comme je l'ai fait pour Google Home), ce qui devrait simplifier les choses.

**Comment by Aymkdn** [comment]
Voilà j'ai créé des applets : https://aymkdn.github.io/assistant-plugins/?plugin=livebox#utilisation

Si tu peux toutes les tester et me dire celles qui fonctionnent / ne fonctionnent pas ?

Merci

**Comment by bedope** [comment]
Bonjour Aymkdn,

Merci pour ton travail.
J'avais en effet repris les applets de google donc ça ne pouvait pas marcher...
J'ai tout delete dans IFTTT et repris les nouveaux que tu as créé pour Alexa.
Côté conf sur mon Syno, je n'ai rien touché, juste relancé l'index.js

Après les tests, allume la livebox, elle me dit: désolé quel appareil ?
Pour les autres commandes, elle se tait et ne prend aucune décision.

Comment vérifier si l'interco entre mon syno et Alexa est bonne ?
Quel log je peux trouver pour avancer ?

Merci pour ton aide.

**Comment by Aymkdn** [comment]
Tu dis bien "Alexa déclenche allume la Livebox"?

Car il faut apparemment utiliser le mot clé "déclenche"...

**Comment by bedope** [comment]
Non pas de changement.

**Comment by Aymkdn** [comment]
Je dirais que le problème vient de Alexa / IFTTT. Essaie de créer une applet IFTTT simple et de tester Alexa pour chercher comment cela fonctionne...

**Comment by bedope** [comment]
J'aimerai comprendre dans un premier temps les interactions entre amazon echo dot (contenant Alexa), pushbullet, IFTTT et mon syno où est installé le plugin.

Je ne vois pas comment mon Echo Dot va de lui même contacter mon Syno sachant qu'il n'a pas de "skill" lui permettant de le faire.

Peux-tu m'éclairer sur le sujet ?

**Comment by Aymkdn** [comment]
Quand tu parles à ton Echo il va regarder si la commande demandée existe dans les applets IFTTT que tu as activées. Si c'est le cas il va enclencher l'applet en question. 

IFTTT prends donc le relai et envoi un message à Pushbullet avec l'instruction / commande qui va bien.

Ton syno, sur lequel tu as installé assistant-plugins, a donc le programme assistant-plugins qui écoute les commandes venant de Pushbullet. Il va donc voir qu'on lui demande d'effectuer une action. Par exemple d'allumer la livebox. Le programme va alors lancer une requête vers la livebox pour lui dire de s'allumer. 

Tu comprends ?

**Comment by bedope** [comment]
Mais pour moi, mon Echo Dot ne détient pas l'applet IFTTT 

Selon moi, la méthode la plus simple serait de développer un skill.
Il existe un kit ASK pour aider au développement.
Cf: https://developer.amazon.com/fr/alexa-skills-kit/?

**Comment by Aymkdn** [comment]
Si, il détient l'applet IFTTT. Quand tu as activé l'applet il a du te demander de te connecter à ton compte Amazon qui est relié à ton Echo.

Les skills ont leur équivalent chez Google et présentent divers désavantages et c'est pourquoi je n'ai pas choisi cette solution avec le Google Home. 

Mais si tu veux développer un skill, fais toi plaisir :-)

**Comment by bedope** [comment]
En effet, mon Echo détient bien ce ddont tu parles.

Dans toutes mes demandes, il me répond désormais:
Désolé, je ne trouve pas ce déclencheur IFTTT

Y a t-il des log sur le Syno qui sont générés ?

**Comment by bedope** [comment]
Bon j'ai fait toute les commandes et c'est pas gagné.

Voici le résultat dans les logs du syno:

[assistant] Assistant v2.0.4 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'livebox' (v1.0.0)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'livebox_soundDown*3' ]
[assistant] Appelle du plugin 'livebox'
[assistant-livebox] Key 114,114,114
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=114&mode=0
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=114&mode=0
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=114&mode=0

Concernant le résultat, rien de probant...

**Comment by Aymkdn** [comment]
Si tu ouvres le lien http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=114&mode=0 dans ton navigateur, il se passe quoi ? Une erreur ? Le son de la Livebox diminue de 1 point ? 

À noter que je ne sais pas si ces commandes fonctionnent avec toutes les Livebox (j'ai une Freebox chez moi). Mais je sais que ça fonctionne puisque plusieurs personnes l'utilisent.
