### ISSUE TITLE
La commande wait ne fonctionne pas

### ISSUE THREAD

**Issue by mawachi** [Aymkdn/assistant-livebox#3]
Bonjour,

Tout d'abord, un gros bravo pour le travail accompli, et un gros merci pour le partage, la documentation et la pédagogie qui l'accompagnent !

J'ai eu l'occasion de tester la création d'une nouvelle applet IFTTT pour livebox et j'ai l'impression que la commande `wait` n'est pas prise en compte.

Je cherchais à créer une applet pour démarrer Netflix sur une livebox à partir de votre outil. Je ne sais pas si les applets sont publiques sur IFTTT, mais au cas où, je mets le lien ici : https://ifttt.com/applets/87421139d-va-sur-netflix-avec-alexa

Le principe est très simple, en suivant vos instructions, je demande à l'assistant-livebox d'envoyer les instructions suivantes à la livebox :

1. Aller sur le menu
2. Attendre 1s
3. Zapper sur tf1
4. Attendre 1s
5. Aller sur le menu
6. Attendre 1s

=> ces étapes peuvent paraître assez étranges, elles ne sont là que pour assurer que la demande fonctionnera qu'on soit sur le menu, ou sur une chaine, ou sur une option du menu livebox

7. Aller vers le bas
8. Aller vers le bas
9. Aller vers la droite
10. Valider avec OK

=> ces étapes permettent de déplacer le curseur jusqu'à la section des "services tiers" de la livebox

11. Attendre 1s
12. Valider avec OK

=> ici, on valide l'entrée dans le service Netflix (qui se trouve être le premier de la liste)

13. Attendre 10s
14. Aller vers la gauche
15. Aller vers la gauche
16. Aller vers la gauche

=> cette dernière étape me permet placer le curseur son mon compte par défaut dans l'interface Netflix

Dans les commandes que vous mettez à disposition, cela se traduit par :

livebox_menu,wait1000,zappe sur la 1,wait1000,menu,wait1000,down,down,right,ok,wait1000,ok,wait10000,left,left,left

Comme vous pouvez le constater, afin de laisser le temps à la box de valider certaines étapes, j'ai glissé quelques `wait`, qu'il faudra peut-être affiner par la suite.
Lors de l'exécution des commandes, une erreur "commande wait1000 inconnue" survient.

En analysant le code, j'ai cru lire que :
- toutes les commandes doivent être référencées dans le tableau `commandes` défini en début de script
- mais que ce tableau ne contient que des commandes se traduisant par des appels au niveau de la livebox

Sauf que `wait` n'est pas une commande avec une implémentation au niveau de la livebox, mais une commande que vous avez ajoutée pour temporiser l'action de l'assistant. De ce fait, elle n'a pas son équivalent dans le tableau `commandes`.

Sans équivalence, au niveau de la ligne suivante :

https://github.com/Aymkdn/assistant-livebox/blob/9d75f7a6f4226f2e47f6964d19b8eef008f6bdf6/livebox.js#L286

la commande tombe inexorablement dans le `reject`.

De mon côté, pour solutionner le problème, j'ai remplacé ça :

```js
} else {
	key = _this.commandes[cmd];
}
```

Par ça :

```js
} else {
	if (/wait\d+/.test(cmd)) {
		return Promise.resolve(cmd);
	}
	key = _this.commandes[cmd];
}
```

Ce qui permet de renvoyer le résolve dans le cas d'une commande de type `waitXXXX`.

Merci encore pour votre travail.

**Comment by Aymkdn** [comment]
Super ! Merci :-)

N'ayant pas de livebox, je ne peux donc pas tester ^^ Je te fais confiance pour le code, et je viens de publier la v1.1.2 avec ta modification !

**Comment by mawachi** [comment]
Quelle réactivité !

Bravo encore pour ton travail !
