### ISSUE TITLE
Debugger ?

### ISSUE THREAD

**Issue by pioroman** [Aymkdn/assistant-livebox#4]
Comment faire pour debugger l'assistant-livebox ?

**Comment by Aymkdn** [comment]
C'est à dire ? Quel est le problème ?

Tu as des pistes là : https://github.com/Aymkdn/assistant-plugins/wiki/Questions-Fréquentes

**Comment by pioroman** [comment]
Bonjour... merci j'ai regarde .. mon probleme doit etre ailleurs... je pense que le lien entre Alexa et IFTT ne fct pas...  car lorsque je dis:

Alexa declenche zappe sur tf1... il me dit Desole je ne trouve pas ce declancheur IFTTT..  j'ai regarde dans l'appli d'alex et sur IFTTT et tout a l'air ok... j'ai bien sur ajouter qq applets pour sur IFTTT... 

Synology : 6.2.1 avec Alexa sur Sonos

**Comment by pioroman** [comment]
root@mynas:~/assistant-plugins# node index.js
[assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'livebox' (v1.1.2)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet

**Comment by Aymkdn** [comment]
> Desole je ne trouve pas ce declancheur IFTTT

Ce problème n'est pas lié à `assistant-plugins` mais à la connexion entre Alexa et IFTTT. Il te faut donc regarder par là.

**Comment by pioroman** [comment]
Oui oui.. il faut que je regarde comment avoir plus de log de ce cote la...

**Comment by Aymkdn** [comment]
Je ferme cet issue. N'hésite pas à continuer à poster ici si tu as d'autres questions liées.

**Comment by pioroman** [comment]
Voila, j'ai reussi a envoyer des commandes a IFTTT mais j'ai du changer la commande en plus court... au lieu de Zappe sur M6, j'ai mis m6 et ca passe sinon il ne reconnait pas la commande...

pushbulet recoit bien la notification aussi... je vais tester avec l'assistant maintenant

donc Alexa declenche m6 au lieu de declenche zappe sur m6...

est-ce un probleme de langue sur IFTTT ?

**Comment by Aymkdn** [comment]
C'est un problème d'Alexa en fait. Elle interprète ce qu'on souhaite dire, là où Google Home est beaucoup plus précis.

Par exemple, avec Google Home et IFTTT on a seulement une seule applet *zappe sur $* et ensuite Google se débrouille pour comprendre la chaine. Mais Alexa ne propose pas cela et préfère "prendre des mots" de l'expression pour les associer. Donc si tu mets juste "M6" à chaque fois que tu vas donner une phrase "déclenche" avec le mot "M6" il va l'associer à cet applet ("mets la chaine M6" par exemple).

Personnellement, je préfère la façon dont c'est géré par Google Home. Aussi Alexa oblige à dire le mot "déclenche" qui rend la phrase bizarre...

**Comment by pioroman** [comment]
ok j'ai reussi a envoyer une commande l'assitant mais ca change pas de chaine..


root@mynas:~/assistant-plugins# node index.js
[assistant] Assistant v2.0.5 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'livebox' (v1.1.2)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Prêt à écouter les commandes via PushBullet
[assistant] Commande reçue:  [ 'livebox_zappe sur M6' ]
[assistant] Appelle du plugin 'livebox'
[assistant-livebox] Zappe sur m6 (6)
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=518&mode=0

**Comment by pioroman** [comment]
j'ai l'impression que le port 8080 n'est pas ouvert sur la livebox play

**Comment by pioroman** [comment]
C:\Users\admin>telnet 192.168.1.1:8080
Connecting To 192.168.1.1:8080...Could not open connection to the host, on port 23: Connect failed

**Comment by Aymkdn** [comment]
Faire un telnet n'est pas très intéressant (surtout sur le port 23). Pour tester tu peux juste ouvrir http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=518&mode=0 dans ton navigateur.

Tu peux aussi (comme [expliqué là](https://aymkdn.github.io/assistant-plugins/?plugin=livebox#param-tre-ip_box)) ouvrir http://livebox/ pour vérifier que l'IP est la bonne.

**Comment by pioroman** [comment]
zut il a pas pris le port pour le telnet.. voila

C:\Users\admin>telnet 192.168.1.1 8080
Connecting To 192.168.1.1...Could not open connection to the host, on port 8080: Connect failed


avec un browser j'ai "connecting" et c'est tout..

This site can’t be reached 192.168.1.1 took too long to respond.
Search Google for 192 168 8080 remote Control cmd
ERR_CONNECTION_TIMED_OUT

L'ip de ma box est bien 192.168.1.1

C:\Users\admin>ipconfig

Windows IP Configuration


Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::359f:abdb:8949:add5%3
   IPv4 Address. . . . . . . . . . . : 192.168.1.100
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1

**Comment by Aymkdn** [comment]
L'IP ne doit pas être bonne. Suis [les instructions](https://aymkdn.github.io/assistant-plugins/?plugin=livebox#param-tre-ip_box).

**Comment by pioroman** [comment]
j'ai fait un nmap sur la livebox et le port 8080 n'est pas ouvert

Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-03 09:47 Romance Standard Time

NSE: Loaded 148 scripts for scanning.

NSE: Script Pre-scanning.

Initiating NSE at 09:47

Completed NSE at 09:47, 0.00s elapsed

Initiating NSE at 09:47

Completed NSE at 09:47, 0.00s elapsed

Initiating ARP Ping Scan at 09:47

Scanning 192.168.1.1 [1 port]

Completed ARP Ping Scan at 09:47, 0.46s elapsed (1 total hosts)

Initiating Parallel DNS resolution of 1 host. at 09:47

Completed Parallel DNS resolution of 1 host. at 09:47, 5.52s elapsed

Initiating SYN Stealth Scan at 09:47

Scanning 192.168.1.1 [65535 ports]

Discovered open port 80/tcp on 192.168.1.1

Discovered open port 445/tcp on 192.168.1.1

Discovered open port 443/tcp on 192.168.1.1

Discovered open port 139/tcp on 192.168.1.1

Discovered open port 53/tcp on 192.168.1.1

SYN Stealth Scan Timing: About 21.71% done; ETC: 09:50 (0:01:52 remaining)

SYN Stealth Scan Timing: About 56.41% done; ETC: 09:49 (0:00:47 remaining)

Discovered open port 631/tcp on 192.168.1.1

Completed SYN Stealth Scan at 09:49, 91.51s elapsed (65535 total ports)

Initiating Service scan at 09:49

**Comment by pioroman** [comment]
c'est peut etre sur le decodeur qu'il faut envoyer cette commande ?

**Comment by pioroman** [comment]
voila... il faut envoyer les message sur le Decodeur Livebox et non la livebox...

**Comment by pioroman** [comment]
Scanning 192.168.1.43 [65535 ports]
Discovered open port 8080/tcp on 192.168.1.43
Discovered open port 50995/tcp on 192.168.1.43
Discovered open port 52235/tcp on 192.168.1.43
Discovered open port 42301/tcp on 192.168.1.43

et la c'est bon...

{
    "result":
    {
        "responseCode": "0",
        "message": "ok",
        "data":
        {}
    }
}

**Comment by Aymkdn** [comment]
Comme l'indique le lien que je t'ai donné deux fois : 
> Il s'agit de l'adresse IP de votre décodeur Livebox

**Comment by pioroman** [comment]
Ok pour les autres... chez Orange il y 2 boxes:

La Livebox qui est par default 192.168.1.1
et la Livebox TV qui est en DHCP

**Comment by pioroman** [comment]
En tous les cas, merci 1000 fois pour ton travail et ton aide.. !!!! je vais faire un DHCP static pour le decodeur et changer la config de l'assistant...

Suggestion :
Faudrait changer cette phrase qui m'a induit en erreur...

"Si la configuration de la Livebox n'a pas été modifiée, l'IP par défaut devrait être la bonne."

Le décodeur TV ne sera jamais en 192.168.1.1.. peut etre meme mettre 192.168.1.x dans le fichier de configuration...

aussi mets bien "décodeur TV Livebox"  a la place de "décodeur Livebox" car c'est facile de se tromper :-)

voila voila je crois que ca va fct chez moi... apparemment on est que 9 a utiliser l'applet :-)

**Comment by Aymkdn** [comment]
J'imagine que peu de bidouilleurs ont des Livebox et qu'ils se tournent plus vers la Freebox ^^ J'ai créé le plugin avec l'aide d'un utilisateur de Livebox car j'ai pensé que ça pouvait servir à d'autres :-)

Je vais modifier l'aide, oui. Merci.

**Comment by pioroman** [comment]
bizzare la box TV  n'a pas l'air stable... la premiere commande http est bien passe et apres elle s'est bloque.. ah moins que ca soit mon nmap qui l'a tuee... je reteste...

Il n'y a que Orange/SFR qui passe la fibre dans ma rue... Free pas encore... d'ailleurs on a hate de voir cette V7 sortir demain

**Comment by pioroman** [comment]
ok je confirme ca fct bien apres reboot.. le nmap avait tue la box TV...

Livebox TV play de 2016... 
Synology
Alexa sur Sonos

avec Applets racourcies... donc commandes du genre "Alexa declenche m6"

**Comment by pioroman** [comment]
Pour le Synology, j'ai trouver une facon plus facile pour lancer l'assistant que d'installer OPKG, CRON, etc..

Il faut utiliser le Scheuler ds la GUI, et lancer le script at boot time..

Je joins un screenshot

la commande que je lance: 

node /root/assistant-plugins/index.js > /var/log/assistant-plugins.log &


![synology_scheduler](https://user-images.githubusercontent.com/45542956/49371083-8fd09780-f6f6-11e8-97d6-4456bec914e8.JPG)
