### ISSUE TITLE
Double livebox HD

### ISSUE THREAD

**Issue by baya44** [Aymkdn/assistant-livebox#6]
Est il possible de pouvoir gérer 2 box tv? 
Cela marche très bien pour ma box principale, mais j'ai une seconde box que j'aimerais pouvoir utiliser de la même façon. 
Merci de votre aide et bravo pour le travail effectué!

**Comment by Aymkdn** [comment]
Pour cela il faudrait tout dédoubler (créer un autre compte Pushbullet, avoir un autre assistant-plugins qui tourne, avoir des applets IFTTT avec un autre mot clé que "Livebox", etc). Pas simple.

Ou alors il faudrait modifier ce plugin pour permettre l'utilisation de plusieurs Livebox – mais n'ayant pas de Livebox, ni le temps, il faudra faire ça vous-même et ensuite faire un Pull Requests.

**Comment by baya44** [comment]
En effet cela n'est pas vraiment pratique de doubler les comptes partout. 
De ce que j'ai regardé dans les scripts, je pense qu'en dupliquant les commandes du style livebox_on et livebox2_on ou chaque commande ping l'IP qui convient à configurer cela devrait être possible. Je n'ai pas vraiment les capacités pour modifier le code, mais je vais essayer de faire quelques tests, et de comprendre surtout l'arborescence des différents appels de fonctions.

**Comment by baya44** [comment]
J'ai réussi à le faire fonctionner. J'ai utiliser votre tuto d'exemple pour ajouter un nouvel assistant, j'ai donc dupliqué le module livebox en renommant livebox2 et en indiquant en dur l'IP de mon second décodeur. Ne sachant pas si je pouvais ajouter une seconde IP, j'ai trouvé ce système plus simple. 
Biensur il faut refaire les triggers sur IFTTT, mais cela marche sans soucis et sans avoir faire tourner un second deamon avec un second compte pushbullet/IFTTT.
En espérant que cela soit utile pour d'autre personne qui utilise plusieurs décodeur.

**Comment by Aymkdn** [comment]
Cool!
