### ISSUE TITLE
Personnalisation des chaînes Orange

### ISSUE THREAD

**Issue by Pilousb** [Aymkdn/assistant-livebox#7]
Bonsoir, je reviens vers vous pour mon problème de personnalisation des chaînes. J'ai une livebox et ne regarde jamais les chaînes Orange car je reçois canalSat en numérique sur la box. Comment puis-je faire pour personnaliser la liste des chaînes ?!
Merci d'avance.

**Comment by Aymkdn** [comment]
Je viens d'ajouter une option `autres_chaines` : https://github.com/Aymkdn/assistant-livebox#param%C3%A8tre-autres_chaines

Je n'ai pas testé (comme je n'ai pas de Livebox je n'utilise pas ce plugin). Mais *en théorie* ça doit marcher :)

Il faut [mettre à jour le plugin](https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-) pour récupérer la v1.1.3 puis modifier le fichier `configuration.json` comme [expliqué](https://github.com/Aymkdn/assistant-livebox#param%C3%A8tre-autres_chaines)

**Comment by Pilousb** [comment]
Merci, je teste ce soir.

**Comment by Pilousb** [comment]
Après un bref essai, j'ai rempli comme ceci mais ça ne fonctionne pas, 

autres_chaines":[
      {"canal":"1001","canal + décalé":"10"},
      {"canal":"1002","nom":"Ma Chaine 2"}
    ]
Est-ce la bonne synthaxe et puis-je substituer la chaîne 10 orange (TMC) par la chaîne 10 de canalsat (Canal + décalé)?!
Merci

**Comment by Aymkdn** [comment]
La bonne syntaxe : 
 ```js
"autres_chaines":[
   {"canal":"10","nom":"canal + décalé"},
   {"canal":"1002","nom":"Ma Chaine 2"}
]
```

**Comment by Pilousb** [comment]
Voici un rapport d'erreur après avoir appliqué la bonne synthaxe : 

[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'livebox' (v1.1.3)
[assistant-livebox] Récupération des chaines terminée !
[assistant-livebox] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-07-22 07:04:35) Connecté ! Prêt à exécuter les ordres.
[assistant] (2020-07-22 07:06:07) Commande reçue:  [ 'livebox_zappe sur Canal + décalé' ]
[assistant] (2020-07-22 07:06:07) Appel du plugin 'livebox'
[assistant-livebox] Erreur : Chaine canal + décalé inconnue
(node:705) UnhandledPromiseRejectionWarning: Chaine canal + décalé inconnue
(node:705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Aymkdn** [comment]
Bizarre car moi ça fonctionne : 
```
[assistant] (2020-07-22 14:26:27) Commande reçue:  [ 'livebox_zappe sur Canal + décalé' ]
[assistant] (2020-07-22 14:26:27) Appel du plugin 'livebox'
[assistant-livebox] Zappe sur canal + décalé (10)
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=513&mode=0
[assistant-livebox] http://192.168.1.1:8080/remoteControl/cmd?operation=01&key=512&mode=0
```

Voici ma configuration : 
```js
{
  "main": {
    "pushbullet_token": "abcdef"
  },
  "plugins": {
    "livebox": {
      "ip_box": "192.168.1.1",
      "autres_chaines":[
        {"canal":"10","nom":"canal + décalé"},
        {"canal":"1002","nom":"Ma Chaine 2"}
      ]
    }
  }
}
```

**Comment by Pilousb** [comment]
Bonne nouvelle !! ça fonctionne...ouf !!
petite subtilité, dans mon cas, pour la prise en compte des modifications du fichier configuration.json de assistant plugins, je dois réinstaller le plugin livebox et ainsi régénérer le fichier chaines_orange.json avec les modifications suivi d'un reboot.
Pour info j’exécute node index.js sur un raspberry.
Il subsiste encore quelques bugs, comme le "Zappe sur M6" qui se transforme en "Zap sur M6" est donc rends l'action impossible mais bon....ça tourne c'est le principal.  ;-)

**Comment by Aymkdn** [comment]
Dans IFTTT, modifie ton applet pour qu'elle prenne en compte la phrase `zappe sur $` mais aussi `zap sur $`
